### ISSUE TITLE
Chaf-Engine需要在本地安装那些库吗？

### ISSUE THREAD

**Issue by Corezcy** [Chaphlagical/Chaf-Engine#1]
B站来的！！！！您好，看了您做的小视频很喜欢这个仿真软件。我最近也需要做一款小仿真的软件，也需要使用glfw+imgui+glm，先学习学习您的代码。
如题，是不是clone下来直接在vs里打开就可以使用了啊？？？谢谢啦！！！

**Comment by Chaphlagical** [comment]
你好，clone的时候需要包含相应的submodule，用`git clone --recursive https://github.com/Chaphlagical/ChafEngine.git`，然后还需要在[https://github.com/premake/premake-core/releases](https://github.com/premake/premake-core/releases)里头下载解压Windows下的release，把里面的`premake5.exe`放在/projects文件夹里，运行那个.bat脚本就可以生成VS文件了，用VS2019的话应该是可以直接正常编译运行了，目前也没有在其他环境下测试过

**Comment by Corezcy** [comment]
> 你好，clone的时候需要包含相应的submodule，用`git clone --recursive https://github.com/Chaphlagical/ChafEngine.git`，然后还需要在https://github.com/premake/premake-core/releases里头下载解压Windows下的release，把里面的`premake5.exe`放在/projects文件夹里，运行那个.bat脚本就可以生成VS文件了，用VS2019的话应该是可以直接正常编译运行了，目前也没有在其他环境下测试过

十分感谢！！！！开始学习代码

**Comment by Corezcy** [comment]
您好，我再请教一下，我也对仿真这块很感兴趣，请教一下需要从什么地方开始学起来呢，需要什么知识储备？？？您有指南之类的吗？？？谢谢啦

**Comment by Chaphlagical** [comment]
> 您好，我再请教一下，我也对仿真这块很感兴趣，请教一下需要从什么地方开始学起来呢，需要什么知识储备？？？您有指南之类的吗？？？谢谢啦

我也是图形学方向入门不久的初学者，目前主要在学几何建模方面的东西，你说的仿真我就大概理解成图形学吧，一般包含几何建模、渲染（绘制）和物理动画（仿真）三个方向，可以看这篇[文章](http://staff.ustc.edu.cn/~lgliu/Resources/CG/What_is_CG.htm)，有一个图形学的社区非常值得关注：[http://games-cn.org/](http://games-cn.org/)，零基础的话可以看闫令琪老师的GAMES101，B站上搜GAMES101就可以找到，物理仿真有Taichi发明者胡渊明老师开的GAMES201，现在还有每周日直播的GAMES102，讲几何建模的，[课程主页](http://staff.ustc.edu.cn/~lgliu/Courses/GAMES102_2020/default.html)。都是质量非常高的中文公开课，相应的课程也会有相关推荐资料。像数学物理这类基础的话因人而异吧，如果想搞学术研究算法的话可能要学多一些数值计算的东西，如果单纯开发向学完GAMES101就可以上手学一些API、开源软件源码之类的东西了

**Comment by Corezcy** [comment]
> > 您好，我再请教一下，我也对仿真这块很感兴趣，请教一下需要从什么地方开始学起来呢，需要什么知识储备？？？您有指南之类的吗？？？谢谢啦
> 
> 我也是图形学方向入门不久的初学者，目前主要在学几何建模方面的东西，你说的仿真我就大概理解成图形学吧，一般包含几何建模、渲染（绘制）和物理动画（仿真）三个方向，可以看这篇[文章](http://staff.ustc.edu.cn/~lgliu/Resources/CG/What_is_CG.htm)，有一个图形学的社区非常值得关注：http://games-cn.org/，零基础的话可以看闫令琪老师的GAMES101，B站上搜GAMES101就可以找到，物理仿真有Taichi发明者胡渊明老师开的GAMES201，现在还有每周日直播的GAMES102，讲几何建模的，[课程主页](http://staff.ustc.edu.cn/~lgliu/Courses/GAMES102_2020/default.html)。都是质量非常高的中文公开课，相应的课程也会有相关推荐资料。像数学物理这类基础的话因人而异吧，如果想搞学术研究算法的话可能要学多一些数值计算的东西，如果单纯开发向学完GAMES101就可以上手学一些API、开源软件源码之类的东西了

十分感谢！！！！我解释一下为什么称其为仿真，目前在做自动驾驶仿真平台的地图场景编辑器，需要渲染地图之类的。再次感谢！！！
