### ISSUE TITLE
目前可以提供结果图片吗

### ISSUE THREAD

**Issue by logic-three-body** [Chaphlagical/Chaf-Engine#2]
目前您可以提供一些引擎渲染的图片放在readme里吗

**Comment by Chaphlagical** [comment]
才发现之前的链接失效了hhh，现在更新好了

**Comment by logic-three-body** [comment]
多谢大佬，最近跟着learnopengl学，希望参考您的引擎自己也写一个渲染器巩固一下😊


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wenbo Chen ***@***.***&gt;
发送时间: 2021年10月1日 21:25
收件人: Chaphlagical/Chaf-Engine ***@***.***&gt;
抄送: l3d ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Chaphlagical/Chaf-Engine] 目前可以提供结果图片吗 (#2)





 
才发现之前的链接失效了hhh，现在更新好了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
